/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CalendarCapabilitiesResponse {
    #[serde(rename = "account_id")]
    pub account_id: String,
    #[serde(rename = "provider_id")]
    pub provider_id: String,
    /// Per-account feature gate. The renderer reads these to enable/ disable form fields (recurrence pickers, attendee inputs, etc.) based on what the underlying provider supports. 
    #[serde(rename = "capabilities")]
    pub capabilities: std::collections::HashMap<String, serde_json::Value>,
}

impl CalendarCapabilitiesResponse {
    pub fn new(account_id: String, provider_id: String, capabilities: std::collections::HashMap<String, serde_json::Value>) -> CalendarCapabilitiesResponse {
        CalendarCapabilitiesResponse {
            account_id,
            provider_id,
            capabilities,
        }
    }
}

