/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Channel : A chat conversation. The same struct backs both group channels (`type: channel | private`) and direct-message threads (`type: im | mpim`); the `Channels` and `DirectMessages` HTTP surfaces filter on `type` to give each its dedicated URL space. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Channel {
    #[serde(rename = "id")]
    pub id: String,
    /// Registered provider id (e.g. `slack`, `native-chat`). 
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    /// Provider-specific. Common canonicals: `channel` and `private` (group channels), `im` (1:1 DM), `mpim` (group DM). 
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "topic", skip_serializing_if = "Option::is_none")]
    pub topic: Option<String>,
    #[serde(rename = "isMember")]
    pub is_member: bool,
    #[serde(rename = "isArchived")]
    pub is_archived: bool,
    #[serde(rename = "memberCount", skip_serializing_if = "Option::is_none")]
    pub member_count: Option<i32>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl Channel {
    /// A chat conversation. The same struct backs both group channels (`type: channel | private`) and direct-message threads (`type: im | mpim`); the `Channels` and `DirectMessages` HTTP surfaces filter on `type` to give each its dedicated URL space. 
    pub fn new(id: String, name: String, r#type: String, is_member: bool, is_archived: bool) -> Channel {
        Channel {
            id,
            provider: None,
            account_id: None,
            name,
            r#type,
            description: None,
            topic: None,
            is_member,
            is_archived,
            member_count: None,
            created_at: None,
        }
    }
}

