/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Comment : Threaded comment on a note. Top-level comments have `parentCommentId: null`; replies set it to the parent comment's id. `blockId` anchors the comment to a specific block; comments without a `blockId` are note-level (\"general\") comments. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Comment {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "noteId")]
    pub note_id: String,
    #[serde(rename = "parentCommentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_comment_id: Option<Option<String>>,
    #[serde(rename = "blockId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub block_id: Option<Option<String>>,
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "author")]
    pub author: Box<models::CommentAuthor>,
}

impl Comment {
    /// Threaded comment on a note. Top-level comments have `parentCommentId: null`; replies set it to the parent comment's id. `blockId` anchors the comment to a specific block; comments without a `blockId` are note-level (\"general\") comments. 
    pub fn new(id: String, note_id: String, body: String, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>, author: models::CommentAuthor) -> Comment {
        Comment {
            id,
            note_id,
            parent_comment_id: None,
            block_id: None,
            body,
            created_at,
            updated_at,
            author: Box::new(author),
        }
    }
}

