/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InitChunkedUploadResponse {
    #[serde(rename = "sessionId")]
    pub session_id: String,
    #[serde(rename = "blocksToUpload")]
    pub blocks_to_upload: Vec<String>,
    /// Blocks the platform already has and the client can skip (content-addressed deduplication). 
    #[serde(rename = "blocksAlreadyExist")]
    pub blocks_already_exist: Vec<String>,
    #[serde(rename = "deduplicationPct")]
    pub deduplication_pct: f64,
    #[serde(rename = "estimatedUploadSize")]
    pub estimated_upload_size: i64,
}

impl InitChunkedUploadResponse {
    pub fn new(session_id: String, blocks_to_upload: Vec<String>, blocks_already_exist: Vec<String>, deduplication_pct: f64, estimated_upload_size: i64) -> InitChunkedUploadResponse {
        InitChunkedUploadResponse {
            session_id,
            blocks_to_upload,
            blocks_already_exist,
            deduplication_pct,
            estimated_upload_size,
        }
    }
}

