/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SpatioConnection : OAuth/native integration descriptor. Open shape — categories add provider-specific capability flags. Treat unknown fields as additive. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpatioConnection {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "authType", skip_serializing_if = "Option::is_none")]
    pub auth_type: Option<String>,
    #[serde(rename = "connected", skip_serializing_if = "Option::is_none")]
    pub connected: Option<bool>,
    #[serde(rename = "connectedAccounts", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub connected_accounts: Option<Option<Vec<std::collections::HashMap<String, serde_json::Value>>>>,
    #[serde(rename = "capabilities", skip_serializing_if = "Option::is_none")]
    pub capabilities: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "gradientFrom", skip_serializing_if = "Option::is_none")]
    pub gradient_from: Option<String>,
    #[serde(rename = "gradientTo", skip_serializing_if = "Option::is_none")]
    pub gradient_to: Option<String>,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
}

impl SpatioConnection {
    /// OAuth/native integration descriptor. Open shape — categories add provider-specific capability flags. Treat unknown fields as additive. 
    pub fn new(id: String) -> SpatioConnection {
        SpatioConnection {
            id,
            name: None,
            category: None,
            description: None,
            auth_type: None,
            connected: None,
            connected_accounts: None,
            capabilities: None,
            gradient_from: None,
            gradient_to: None,
            icon: None,
        }
    }
}

