/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateEventRequest : Sparse update. `updates` is a free-form map of fields to change; only keys present are applied. The server-side capability gate rejects fields that the underlying provider doesn't support. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateEventRequest {
    #[serde(rename = "account_id")]
    pub account_id: String,
    #[serde(rename = "updates")]
    pub updates: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "send_updates", skip_serializing_if = "Option::is_none")]
    pub send_updates: Option<SendUpdates>,
}

impl UpdateEventRequest {
    /// Sparse update. `updates` is a free-form map of fields to change; only keys present are applied. The server-side capability gate rejects fields that the underlying provider doesn't support. 
    pub fn new(account_id: String, updates: std::collections::HashMap<String, serde_json::Value>) -> UpdateEventRequest {
        UpdateEventRequest {
            account_id,
            updates,
            send_updates: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SendUpdates {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "externalOnly")]
    ExternalOnly,
    #[serde(rename = "none")]
    None,
}

impl Default for SendUpdates {
    fn default() -> SendUpdates {
        Self::All
    }
}

